/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class ChoicesData {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected ChoicesData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChoicesData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_ChoicesData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ChoicesData() {
    this(AdaptiveCardObjectModelJNI.new_ChoicesData__SWIG_0(), true);
  }

  public ChoicesData(String type, String dataset, String value, int count, int skip) {
    this(AdaptiveCardObjectModelJNI.new_ChoicesData__SWIG_1(type, dataset, value, count, skip), true);
  }

  public boolean ShouldSerialize() {
    return AdaptiveCardObjectModelJNI.ChoicesData_ShouldSerialize(swigCPtr, this);
  }

  public String Serialize() {
    return AdaptiveCardObjectModelJNI.ChoicesData_Serialize(swigCPtr, this);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.ChoicesData_SerializeToJsonValue(swigCPtr, this), true);
  }

  public String GetType() {
    return AdaptiveCardObjectModelJNI.ChoicesData_GetType__SWIG_0(swigCPtr, this);
  }

  public void SetType(String type) {
    AdaptiveCardObjectModelJNI.ChoicesData_SetType(swigCPtr, this, type);
  }

  public String GetDataset() {
    return AdaptiveCardObjectModelJNI.ChoicesData_GetDataset__SWIG_0(swigCPtr, this);
  }

  public void SetDataset(String dataset) {
    AdaptiveCardObjectModelJNI.ChoicesData_SetDataset(swigCPtr, this, dataset);
  }

  public String GetValue() {
    return AdaptiveCardObjectModelJNI.ChoicesData_GetValue__SWIG_0(swigCPtr, this);
  }

  public void SetValue(String value) {
    AdaptiveCardObjectModelJNI.ChoicesData_SetValue(swigCPtr, this, value);
  }

  public int GetCount() {
    return AdaptiveCardObjectModelJNI.ChoicesData_GetCount__SWIG_0(swigCPtr, this);
  }

  public void SetCount(int count) {
    AdaptiveCardObjectModelJNI.ChoicesData_SetCount(swigCPtr, this, count);
  }

  public int GetSkip() {
    return AdaptiveCardObjectModelJNI.ChoicesData_GetSkip__SWIG_0(swigCPtr, this);
  }

  public void SetSkip(int skip) {
    AdaptiveCardObjectModelJNI.ChoicesData_SetSkip(swigCPtr, this, skip);
  }

  public static ChoicesData Deserialize(ParseContext context, JsonValue root) {
    long cPtr = AdaptiveCardObjectModelJNI.ChoicesData_Deserialize(ParseContext.getCPtr(context), context, JsonValue.getCPtr(root), root);
    return (cPtr == 0) ? null : new ChoicesData(cPtr, true);
  }

  public static ChoicesData DeserializeFromString(ParseContext context, String jsonString) {
    long cPtr = AdaptiveCardObjectModelJNI.ChoicesData_DeserializeFromString(ParseContext.getCPtr(context), context, jsonString);
    return (cPtr == 0) ? null : new ChoicesData(cPtr, true);
  }

}
